### ISSUE TITLE
Docker image :latest not pointing to released version

### ISSUE THREAD

**Issue by tribut** [isso-comments/isso#1012]
## Checklist
- [x] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/isso-comments/isso/issues), but my issue has not already been reported

## What is not working?
The docker image `ghcr.io/isso-comments/isso:latest` is apparently updated for every commit. This conflicts with the information in the README, which states:

> A Docker image with the **latest stable release** is provided at ghcr.io/isso-comments/isso:latest

(highlight mine)

**Comment by jelmer** [comment]
I think if we want to provide a tag like this, we shouldn't call it latest but rather create a separate tag with a clearer name ("release") ?

That said, I think it's good practice to pin a specific release so maybe we should just drop the documentation.

**Comment by ix5** [comment]
See https://github.com/isso-comments/isso/pull/1014
